-- first_name, Last_name role_id manager_id
-- vl ro int null if manager, corrosponding int of employee id if manager
-- val rojas 1 null
-- alex green 2 1 because id 1 is his manager
-- to determine the id number corrosponding to the employee role 
-- title salary dept id
-- lawyer, int, dept id int you choose with it
-- this is how you match it to the role id as well
-- insert into should specify each:
-- dept (name) role (title, salary, department_id) employee(first name, last name, role id, manager id)